const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/haiku-libro-consultas-v1.js','utf8');
const fixture=()=>({q:{nombre:'andres'},archivo:'Libro de reservas.xlsx',aseos:[],anotaciones:[],advertencias:['Cobertura de prueba'],reservas:[{titular:'Andrés Mahecha',cabana:6,fecha_checkin:'2026-10-10',fecha_checkout:'2026-10-12',noches:2,estado_confirmacion:'confirmada_por_color',estado_operativo:'no_determinado',adultos:2,ninos:0,mascotas:0,rut_documento:'Documento de prueba',correo:'prueba@example.test',telefono:'Sin dato',operador:'CO',fecha_ingreso_libro:'2026-09-01',notas_importantes:['Llegará tarde'],pagos_pendientes:['Manager pendiente'],servicios:[{concepto:'Leña',texto_original:'Solicita leña'}],pagos:[],pagos_sin_asociacion:[],advertencias:['Confirmar horario'],cobertura_pagos:true,coordenadas_origen:{hoja:'Oct26',celda:'AN8'}}]});
class Element {constructor(tag){this.tag=tag;this.children=[];this.textContent='';this.style={};}append(...c){this.children.push(...c)}replaceChildren(...c){this.children=c}}
function harness(){const ctx={document:{querySelector:()=>null,createElement:t=>new Element(t)},addEventListener(){},HAIKU_LIBRO_SEMANTICA:require('../js/haiku-libro-semantica-v1.js')};vm.runInNewContext(source.replace('const apiConsultas =','root.renderConsultaTest = renderizarConsultaLibro; const apiConsultas ='),ctx);return {render:ctx.renderConsultaTest,out:new Element('div')}}
const nodes=e=>[e,...e.children.flatMap(nodes)],text=e=>nodes(e).map(x=>x.textContent).join('\n');
test('individual Libro card preserves guest, source, dates, notes, services and debt disclaimer without mutation',()=>{const h=harness(),r=fixture(),before=JSON.stringify(r);h.render(h.out,r);const t=text(h.out);for(const value of ['Andrés Mahecha','CAB 6','2026-10-10','2026-10-12','2 noches','AN8','prueba@example.test','Llegará tarde','Solicita leña','no es una certificación de deuda','Cobertura de prueba'])assert.ok(t.includes(value),value);assert.equal(nodes(h.out).filter(x=>x.tag==='article').length,1);assert.equal(nodes(h.out).find(x=>x.tag==='details').open,true);assert.equal(JSON.stringify(r),before)});
test('eight reservations stay compact with their secondary sections collapsed',()=>{const h=harness(),r=fixture();r.reservas=Array.from({length:8},(_,i)=>({...r.reservas[0],titular:'Huésped '+i}));h.render(h.out,r);assert.equal(nodes(h.out).filter(x=>x.tag==='article').length,8);assert.ok(nodes(h.out).filter(x=>x.tag==='details').every(x=>!x.open));assert.match(text(h.out),/8 reservas identificadas/)});
test('payments, unsafe movements, administrative pending and penalties retain all cautions',()=>{const h=harness(),r=fixture(),p={tipo_movimiento:'alojamiento',monto:100000,estado_pago:'registrado_en_libro',texto_original:'Pago original <script>texto</script>',origen:{hoja:'Oct26',celda:'AM30'},bove_pendiente:true,manager_pendiente:true};r.reservas[0].pagos=[p];r.reservas[0].pagos_sin_asociacion=[{...p,tipo_movimiento:'penalidad',penalidad_porcentaje:10,monto_penalidad:10000,saldo_por_pagar:90000}];h.render(h.out,r);const t=text(h.out);for(const value of ['Pago asociado','SIN asociación segura','BOVE Manager','No equivale a deuda','No se suma como pago','Pago original <script>texto</script>'])assert.ok(t.includes(value),value);assert.ok(!nodes(h.out).some(n=>n.tag==='script'))});
test('routing keeps versions and comparison ahead of the new presentation; unrelated Haku files unchanged',()=>{assert.match(source,/if \(result.q.versiones\) renderizarVersiones\(out, result\);\s*else if \(result.q.comparar\) renderizarComparacion\(out, result\);\s*else renderizarConsultaLibro\(out, result\);/);assert.match(source,/const esLibro = texto =>/)});
module.exports={fixture,source};

